LRSD-5420
liferay-customer-solutions/liferay-portal pull request #302
Opened 2024-09-25 19:57 UTC by abfranca

2024-09-25 19:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-09-25 19:57 UTC, abfranca commented
ci:test:sf

2024-09-25 19:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7230/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7230/jenkins-report.html">here</a>.</b></p>

2024-09-25 20:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/72260c9f00fdd54729e350dc4a62c1338478984f">72260c9f00fdd54729e350dc4a62c1338478984f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/LRSD-5420">LRSD-5420</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/f605195ea044099f04ee6d8008814fdb39c549f3">f605195ea044099f04ee6d8008814fdb39c549f3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7230/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7230/jenkins-report.html">here</a>.</h5></details></html>

2024-09-25 20:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7230/">test-portal-source-format#7230</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7230/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-customer-solutions/liferay-portal/pull/302">liferay-customer-solutions#302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/21723112">[master] ci:test:sf - abfranca &gt; liferay-customer-solutions - PR#302 - 2024-09-25[12:57:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>21723112<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/27617/">publish-testray-report#27617</a><br/></div></div>

2024-09-25 23:01 UTC, amosfong commented
@abfranca did you see the confluence article? I think there is more stuff there. Or is this a partial PR first?

2024-09-26 13:01 UTC, abfranca commented
@amosfong yeah, i've asked about that on our channel, since the confluence article mentions other tickets for other steps i thought there would be more tickets like this for the other missing parts. i'll be working on them now, thanks!

2024-09-26 13:50 UTC, jennyhchen requested changes

2024-09-27 17:23 UTC, abfranca commented on workspaces/liferay-customer-workspace/client-extensions/liferay-customer-site-initializer-quickstart/client-extension.yaml
>      siteExternalReferenceCode: LIFERAY_CUSTOMER
Done!

2024-09-27 17:23 UTC, abfranca commented
ci:test:sf

2024-09-27 17:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/83875f6e04832bd5a1716916d4d31748f28be488">83875f6e04832bd5a1716916d4d31748f28be488</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/LRSD-5420">LRSD-5420</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/86c351218a94039d831c5ccd30de205f3a2c4eea">86c351218a94039d831c5ccd30de205f3a2c4eea</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7244/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7244/jenkins-report.html">here</a>.</h5></details></html>

2024-09-27 17:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7244/">test-portal-source-format#7244</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7244/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-customer-solutions/liferay-portal/pull/302">liferay-customer-solutions#302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/24633520">[master] ci:test:sf - abfranca &gt; liferay-customer-solutions - PR#302 - 2024-09-27[10:23:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>24633520<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/27665/">publish-testray-report#27665</a><br/></div></div>

2024-09-27 19:28 UTC, amosfong commented
how come you removed a bunch of test accounts?

2024-09-27 19:37 UTC, abfranca commented
@amosfong it was on the doc, should i add them back?

2024-09-27 19:41 UTC, amosfong commented
oh...haha yea sorry that was unclear. These were originally steps for UAT and prod. Yea can you add them back, thanks!

2024-09-27 19:52 UTC, abfranca commented
@amosfong they're back!

2024-09-27 20:37 UTC, amosfong commented on workspaces/liferay-customer-workspace/client-extensions/liferay-customer-instance-settings/client-extension.yaml
> +# Currently not working
Can you remove these comments and put it in the ticket instead?

2024-09-27 22:31 UTC, ryanschuhler commented
closing for https://github.com/liferay-customer-solutions/liferay-portal/pull/306 (also removed the instance settings cx for now)

2024-09-27 22:31 UTC, closed without merging