ISSD-1822 [CP 2.0] Release Notes page - 1st tab: Release Highlights
liferay-customer-solutions/liferay-portal pull request #37
Opened 2024-03-21 19:00 UTC by samuelleolopes

[ISSD-1822](https://liferay.atlassian.net/browse/ISSD-1822)

2024-03-21 19:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-03-21 21:00 UTC, kylembischof requested changes
when i run `gw formatSource && yarn format` it lists out some errors. can you check these?

```
/home/me/dev/projects/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group/src/customer-portal/fragments/release-notes-redirect/index.js
  6:18  error  'layoutMode' is not defined.  no-undef
  7:21  error  'layoutMode' is not defined.  no-undef

/home/me/dev/projects/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group/src/customer-portal/fragments/release-notes-tabs/index.js
  6:18  error  'fragmentElement' is not defined.  no-undef
  7:24  error  'fragmentElement' is not defined.  no-undef
  8:18  error  'layoutMode' is not defined.  no-undef
  14:2  error  'fragmentElement' is not defined.  no-undef
  15:34  error  'fragmentNamespace' is not defined.  no-undef
  20:2  error  'fragmentElement' is not defined.  no-undef
  21:34  error  'fragmentNamespace' is not defined.  no-undef
  26:7  error  'configuration' is not defined.  no-undef

✖ 10 problems (10 errors, 0 warnings)
```

2024-03-22 13:15 UTC, samuelleolopes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/ddm-templates/release-notes-dropdown/ddm-template.ftl
> +				value = getValueForElementId(elemento.id);
Corrected to "element". thanks

2024-03-22 14:31 UTC, samuelleolopes commented
> when i run `gw formatSource && yarn format` it lists out some errors. can you check these?
> 
> ```
> /home/me/dev/projects/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group/src/customer-portal/fragments/release-notes-redirect/index.js
>   6:18  error  'layoutMode' is not defined.  no-undef
>   7:21  error  'layoutMode' is not defined.  no-undef
> 
> /home/me/dev/projects/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group/src/customer-portal/fragments/release-notes-tabs/index.js
>   6:18  error  'fragmentElement' is not defined.  no-undef
>   7:24  error  'fragmentElement' is not defined.  no-undef
>   8:18  error  'layoutMode' is not defined.  no-undef
>   14:2  error  'fragmentElement' is not defined.  no-undef
>   15:34  error  'fragmentNamespace' is not defined.  no-undef
>   20:2  error  'fragmentElement' is not defined.  no-undef
>   21:34  error  'fragmentNamespace' is not defined.  no-undef
>   26:7  error  'configuration' is not defined.  no-undef
> 
> ✖ 10 problems (10 errors, 0 warnings)
> ```

Resolved with "Liferay.<element>"

2024-03-22 15:27 UTC, samuelleolopes commented
> when i run `gw formatSource && yarn format` it lists out some errors. can you check these?
> 
> ```
> /home/me/dev/projects/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group/src/customer-portal/fragments/release-notes-redirect/index.js
>   6:18  error  'layoutMode' is not defined.  no-undef
>   7:21  error  'layoutMode' is not defined.  no-undef
> 
> /home/me/dev/projects/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group/src/customer-portal/fragments/release-notes-tabs/index.js
>   6:18  error  'fragmentElement' is not defined.  no-undef
>   7:24  error  'fragmentElement' is not defined.  no-undef
>   8:18  error  'layoutMode' is not defined.  no-undef
>   14:2  error  'fragmentElement' is not defined.  no-undef
>   15:34  error  'fragmentNamespace' is not defined.  no-undef
>   20:2  error  'fragmentElement' is not defined.  no-undef
>   21:34  error  'fragmentNamespace' is not defined.  no-undef
>   26:7  error  'configuration' is not defined.  no-undef
> 
> ✖ 10 problems (10 errors, 0 warnings)
> ```


Hi @kylembischof, It fixed with /* eslint-disable no-undef */, thanks @jairmedeiros

2024-03-26 15:44 UTC, kylembischof commented
@jairmedeiros can you please take a look when you have a chance. thanks!

2024-03-27 17:15 UTC, jairmedeiros commented
@samuelleolopes @pedroliveirav I scheduled a meeting tomorrow to discuss about this PR, thanks.

2024-04-01 13:42 UTC, pedroliveirav requested changes

2024-04-02 12:12 UTC, closed without merging

2024-04-10 01:42 UTC, samuelleolopes commented
PR reopened https://github.com/liferay-customer-delivery/liferay-portal/pull/64